# Generated by Django 3.0.1 on 2020-08-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
